<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Shouldly" PrivateAssets="all" />
    <PackageReference Include="xunit.v3.core.mtp-v2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Testing.Platform" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\YHAB.Testing\YHAB.Testing.csproj" />
  </ItemGroup>
</Project>
